import { readFile, writeFile, mkdir, readdir, copyFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const root = path.resolve(web, '../..');
const tokens = JSON.parse(await readFile(path.join(root, 'AwesomeDS/tokens.json'), 'utf8'));
const kebab = s => s.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
const resolve = s => {
  const [family, step] = s.split('.');
  return tokens.reference[family][step];
};
const blocks = Object.entries(tokens.semantic).map(([theme, values]) => `${theme === 'light' ? ':root' : '.dark'} {\n${Object.entries(values).map(([k, v]) => `  --${kebab(k)}: ${resolve(v)};`).join('\n')}\n}`);
blocks.push(`:root {\n${Object.entries(tokens.space).map(([k, v]) => `  --space-${k}: ${v}px;`).join('\n')}\n${Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v}px;`).join('\n')}\n${['fast', 'base', 'slow'].map(k => `  --duration-${k}: ${tokens.motion[k]}ms;`).join('\n')}\n  --ease: ${tokens.motion.ease};\n${Object.entries(tokens.type).flatMap(([k, v]) => [`  --type-${k}: ${v.size}px;`, `  --line-${k}: ${v.line};`, `  --weight-${k}: ${v.weight};`, `  --tracking-${k}: ${v.tracking};`]).join('\n')}\n  --layout-page: ${tokens.layout.page}px;\n  --layout-rail: ${tokens.layout.rail}px;\n  --layout-gutter: ${tokens.layout.gutter}px;\n}`);
const cssPath = path.join(web, 'src/app/globals.css');
const css = await readFile(cssPath, 'utf8');
const generated = `/* CANON START: generated by pnpm sync:canon */\n${blocks.join('\n')}\n/* CANON END */`;
await writeFile(cssPath, css.replace(/\/\* CANON START[\s\S]*?\/\* CANON END \*\//, generated));
async function copySources(dir) {
  for (const entry of await readdir(path.join(root, dir), {
    withFileTypes: true
  })) {
    const relative = path.join(dir, entry.name);
    if (entry.isDirectory()) await copySources(relative);else if (/\.(md|json)$/.test(entry.name)) {
      const dest = path.join(web, 'public/sources', relative);
      await mkdir(path.dirname(dest), {
        recursive: true
      });
      await copyFile(path.join(root, relative), dest);
    }
  }
}
await rm(path.join(web, 'public/sources'), {
  recursive: true,
  force: true
});
for (const folder of ['AwesomeDS', 'Knowledge', 'Plugin']) await copySources(folder);
await writeFile(path.join(root, 'AwesomeDS/preview.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AwesomeDS token preview</title><style>${blocks.join('\n')}body{background:var(--background);color:var(--foreground);font:16px/1.75 system-ui;margin:24px}button{background:var(--primary);color:var(--primary-foreground);padding:12px 24px;border:0;border-radius:var(--radius-md)}main{max-width:800px}section{display:flex;gap:24px;flex-wrap:wrap;margin:24px 0}.swatch{width:140px}i{display:block;height:80px;border:1px solid var(--border);border-radius:var(--radius-md)}</style><main><h1>AwesomeDS tokens</h1><p>White and dark surfaces. Blue decisions. Generated from tokens.json.</p><button onclick="document.documentElement.classList.toggle('dark')">Toggle theme</button><section>${Object.keys(tokens.semantic.light).map(k => `<div class="swatch"><i style="background:var(--${kebab(k)})"></i>${kebab(k)}</div>`).join('')}</section><p>Live component previews: apps/web → /gallery</p></main></html>\n`);
console.log('Canon synced: CSS variables, source files, standalone preview.');
