export const knowledgeArticles = [
  {
    id: "awesome-design-md",
    title: "awesome-design-md",
    topic: "DESIGN.md",
    source: "https://github.com/voltagent/awesome-design-md",
    summary: "公開サイトから抽出した DESIGN.md。言語の型を学ぶ材料。",
    body: "公開サイトの見た目を DESIGN.md に落とし、エージェントへ渡すコレクション。テーマ、色の役割、書体、部品、禁止事項が揃っている。抽出は観察であり、ブランドの公式許諾ではない。",
  },
  {
    id: "awesome-design-md-jp",
    title: "awesome-design-md-jp",
    topic: "DESIGN.md",
    source: "https://github.com/kzhrknt/awesome-design-md-jp",
    summary: "和文組版を含む日本語サービス向け DESIGN.md。",
    body: "日本語 UI 用。和文フォールバック、行間 1.7–2.0、字間、禁則、OpenType、混植が無いとエージェントは詰まった日本語を出す。",
  },
  {
    id: "taste-skill",
    title: "taste-skill",
    topic: "Skill",
    source: "https://github.com/Leonxlnx/taste-skill",
    summary: "生成 UI の既定顔を避けるダイヤルと禁止事項。",
    body: "VARIANCE / MOTION / DENSITY の3ダイヤルと、Inter・紫グラデ・ガラスの禁止。AwesomeDS 本体は低バリアンス、低〜中モーション、中密度で固定する。",
  },
  {
    id: "neropursue-x",
    title: "neropursue（X）",
    topic: "Skill",
    source: "https://x.com/neropursue/status/2089263766428950683",
    summary: "指定投稿は 403。本文は未取得。",
    body: "2026-09-06 時点で HTTP 403。本文は未取得。推測で埋めない。",
  },
  {
    id: "shadcn-ui",
    title: "shadcn/ui",
    topic: "部品",
    source: "https://ui.shadcn.com/docs",
    summary: "コピー配布。部品を自前 DS として育てる。",
    body: "パッケージではなくコピー配布。Open Code と共通インターフェース。既定の zinc と大きな角丸は AwesomeDS トークンに差し替える。",
  },
  {
    id: "assistant-ui",
    title: "assistant-ui",
    topic: "部品",
    source: "https://www.assistant-ui.com/",
    summary: "チャット UI と Elements ギャラリーの情報設計。",
    body: "チャット UI キット。Elements は「名前・短い役割・触れるプレビュー」。このショーケースの情報設計の見本。",
  },
  {
    id: "apple-hig",
    title: "Apple HIG",
    topic: "指針",
    source: "https://developer.apple.com/design/human-interface-guidelines",
    summary: "明快さ、敬意、深さ。タッチと Reduce Motion。",
    body: "明快さ、敬意、深さ。主要操作 44px。フォーカスと Reduce Motion を設定として扱う。",
  },
  {
    id: "material-design",
    title: "Material 3",
    topic: "指針",
    source: "https://m3.material.io/",
    summary: "役割トークン、8dp、状態と動きのセット。",
    body: "色は役割で持つ。8dp。状態をトークン化。サーフェスは3段まで。danger は accent の再利用禁止。",
  },
  {
    id: "duolingo",
    title: "Duolingo",
    topic: "指針",
    source: "https://web.archive.org/web/20260310155248/https://design.duolingo.com/",
    summary: "アクセントは進行に使う。公式サイトはアーカイブ参照。",
    body: "ブランド色は進行と報酬。失敗しても次の一手を残す。公式サイトはアーカイブ経由。Figma Community ファイルは観察用。",
  },
] as const;

export const knowledgeItems = knowledgeArticles.map((item) => ({
  href: `/knowledge#${item.id}`,
  title: item.title,
  topic: item.topic,
  summary: item.summary,
}));
